// Generated by tools/build-wordlist.py from tools/blocked-words.json.
// Do not edit this file. Edit the JSON and run the generator.

// Words this app will not put into a voice that belongs to someone who
// is not here to object.
// 
// Two lists, because they are two different problems. A slur is not somebody's
// grief — it is a weapon, aimed with a voice its owner cannot take back. That one
// is not negotiable. Profanity is refused as well, but the case for it is much
// weaker: grief is not polite, and "I miss you so fucking much" is a real
// sentence a real person writes. It is a separate list behind a separate flag for
// exactly that reason.
//
// This copy is the relay's. See tools/blocked-words.json.

export const REFUSE_PROFANITY = true;

export const SLURS = [
  "chink",
  "coon",
  "dyke",
  "fag",
  "faggot",
  "faggots",
  "gook",
  "half breed",
  "kike",
  "mongoloid",
  "nigga",
  "nigger",
  "niggers",
  "paki",
  "raghead",
  "retard",
  "retarded",
  "retards",
  "sandnigger",
  "shemale",
  "spic",
  "towelhead",
  "trannies",
  "tranny",
  "wetback",
  "خول",
  "زنجي",
  "كافر قذر",
  "متخلف عقليا"
];
export const SLURS_SQUEEZED = [
  "chink",
  "dyke",
  "fag",
  "kike",
  "mongoloid",
  "paki",
  "raghead",
  "retard",
  "retarded",
  "retards",
  "shemale",
  "spic",
  "towelhead",
  "wetback",
  "خول",
  "زنجي",
  "كافر قذر",
  "متخلف عقليا"
];

export const SEXUAL = [
  "anal",
  "blowjob",
  "bukkake",
  "buttplug",
  "creampie",
  "cumshot",
  "cunnilingus",
  "deepthroat",
  "dildo",
  "felching",
  "fleshlight",
  "gangbang",
  "handjob",
  "hentai",
  "jerkoff",
  "masturbate",
  "masturbating",
  "milf",
  "nudes",
  "porn",
  "porno",
  "pornography",
  "rimjob",
  "زب",
  "شرموطه",
  "طيز",
  "عاهره",
  "قحبه",
  "كس",
  "منيوك",
  "نيك"
];
export const SEXUAL_SQUEEZED = [
  "anal",
  "blowjob",
  "creampie",
  "cumshot",
  "dildo",
  "felching",
  "fleshlight",
  "gangbang",
  "handjob",
  "hentai",
  "masturbate",
  "masturbating",
  "milf",
  "nudes",
  "porn",
  "porno",
  "pornography",
  "rimjob",
  "زب",
  "شرموطه",
  "طيز",
  "عاهره",
  "قحبه",
  "كس",
  "منيوك",
  "نيك"
];

export const PROFANITY = [
  "arsehole",
  "asshole",
  "bastard",
  "bitch",
  "bitches",
  "bullshit",
  "cock",
  "cunt",
  "dickhead",
  "fuck",
  "fucked",
  "fucker",
  "fucking",
  "motherfucker",
  "prick",
  "pussy",
  "shit",
  "shitty",
  "slut",
  "twat",
  "wanker",
  "whore",
  "ابن الكلب",
  "العنه",
  "حيوان قذر",
  "خرا",
  "زفت",
  "طز",
  "كسمك",
  "كلب ابن كلب",
  "يلعن"
];
export const PROFANITY_SQUEEZED = [
  "arsehole",
  "bastard",
  "bitch",
  "bitches",
  "cock",
  "cunt",
  "dickhead",
  "fuck",
  "fucked",
  "fucker",
  "fucking",
  "motherfucker",
  "prick",
  "shit",
  "slut",
  "twat",
  "wanker",
  "whore",
  "ابن الكلب",
  "العنه",
  "حيوان قذر",
  "خرا",
  "زفت",
  "طز",
  "كسمك",
  "كلب ابن كلب",
  "يلعن"
];

const STRIP = new Set([
  "\u0640", "\u200C", "\u200D", "\u200E", "\u200F", "\u0670",
  ...Array.from({ length: 0x0660 - 0x064B }, (_, i) => String.fromCharCode(0x064B + i)),
  ...Array.from({ length: 0x06EE - 0x06D6 }, (_, i) => String.fromCharCode(0x06D6 + i)),
]);

const SWAP = {
  "\u0623": "\u0627", "\u0625": "\u0627", "\u0622": "\u0627", "\u0671": "\u0627",
  "\u0649": "\u064A", "\u0629": "\u0647", "\u0624": "\u0648", "\u0626": "\u064A",
  "0": "o", "1": "i", "3": "e", "4": "a", "5": "s", "7": "t", "@": "a", "$": "s",
};

const SEPARATORS = new Set([".", "-", "_", "*", "#", "%", "\u2022", "'", "\u2019"]);
const LETTER = /\p{L}/u;

/** Must agree, character for character, with BlockedWords.normalise in Swift. */
export function normalise(text, squeeze = false) {
  let out = "";
  let previous = " ";
  for (let ch of String(text || "").toLowerCase()) {
    if (SWAP[ch]) ch = SWAP[ch];
    if (STRIP.has(ch)) continue;
    if (!LETTER.test(ch)) ch = " ";
    if (ch === previous && (squeeze || ch === " ")) continue;
    out += ch;
    previous = ch;
  }
  return " " + out.trim() + " ";
}

export function undotted(text) {
  const chars = Array.from(String(text || ""));
  let out = "";
  for (let i = 0; i < chars.length; i++) {
    if (SEPARATORS.has(chars[i]) && i > 0 && i + 1 < chars.length &&
        LETTER.test(chars[i - 1]) && LETTER.test(chars[i + 1])) continue;
    out += chars[i];
  }
  return out;
}

/** The first refused word, or "" if there is none. */
export function refusal(text) {
  const groups = [[SLURS, SLURS_SQUEEZED], [SEXUAL, SEXUAL_SQUEEZED]];
  if (REFUSE_PROFANITY) groups.push([PROFANITY, PROFANITY_SQUEEZED]);
  for (const candidate of [text, undotted(text)]) {
    const plain = normalise(candidate);
    const tight = normalise(candidate, true);
    for (const [words, squeezed] of groups) {
      for (const word of words) if (plain.includes(" " + word + " ")) return word;
      for (const word of squeezed) if (tight.includes(" " + word + " ")) return word;
    }
  }
  return "";
}
