// Generated by tools/build-wordlist.py from tools/blocked-words.json.
// Do not edit this file. Edit the JSON and run the generator.

import Foundation

/// Words this app will not put into a voice that belongs to someone who
/// is not here to object.
/// 
/// Two lists, because they are two different problems. A slur is not somebody's
/// grief — it is a weapon, aimed with a voice its owner cannot take back. That one
/// is not negotiable. Profanity is refused as well, but the case for it is much
/// weaker: grief is not polite, and "I miss you so fucking much" is a real
/// sentence a real person writes. It is a separate list behind a separate flag for
/// exactly that reason.
enum BlockedWords {

    /// Flip this and the slur list is untouched.
    static let refuseProfanity = true

    static let slurs: [String] = [
        "chink",
        "coon",
        "dyke",
        "fag",
        "faggot",
        "faggots",
        "gook",
        "half breed",
        "kike",
        "mongoloid",
        "nigga",
        "nigger",
        "niggers",
        "paki",
        "raghead",
        "retard",
        "retarded",
        "retards",
        "sandnigger",
        "shemale",
        "spic",
        "towelhead",
        "trannies",
        "tranny",
        "wetback",
        "خول",
        "زنجي",
        "كافر قذر",
        "متخلف عقليا"
    ]
    static let slursSqueezed: [String] = [
        "chink",
        "dyke",
        "fag",
        "kike",
        "mongoloid",
        "paki",
        "raghead",
        "retard",
        "retarded",
        "retards",
        "shemale",
        "spic",
        "towelhead",
        "wetback",
        "خول",
        "زنجي",
        "كافر قذر",
        "متخلف عقليا"
    ]

    static let sexual: [String] = [
        "anal",
        "blowjob",
        "bukkake",
        "buttplug",
        "creampie",
        "cumshot",
        "cunnilingus",
        "deepthroat",
        "dildo",
        "felching",
        "fleshlight",
        "gangbang",
        "handjob",
        "hentai",
        "jerkoff",
        "masturbate",
        "masturbating",
        "milf",
        "nudes",
        "porn",
        "porno",
        "pornography",
        "rimjob",
        "زب",
        "شرموطه",
        "طيز",
        "عاهره",
        "قحبه",
        "كس",
        "منيوك",
        "نيك"
    ]
    static let sexualSqueezed: [String] = [
        "anal",
        "blowjob",
        "creampie",
        "cumshot",
        "dildo",
        "felching",
        "fleshlight",
        "gangbang",
        "handjob",
        "hentai",
        "masturbate",
        "masturbating",
        "milf",
        "nudes",
        "porn",
        "porno",
        "pornography",
        "rimjob",
        "زب",
        "شرموطه",
        "طيز",
        "عاهره",
        "قحبه",
        "كس",
        "منيوك",
        "نيك"
    ]

    static let profanity: [String] = [
        "arsehole",
        "asshole",
        "bastard",
        "bitch",
        "bitches",
        "bullshit",
        "cock",
        "cunt",
        "dickhead",
        "fuck",
        "fucked",
        "fucker",
        "fucking",
        "motherfucker",
        "prick",
        "pussy",
        "shit",
        "shitty",
        "slut",
        "twat",
        "wanker",
        "whore",
        "ابن الكلب",
        "العنه",
        "حيوان قذر",
        "خرا",
        "زفت",
        "طز",
        "كسمك",
        "كلب ابن كلب",
        "يلعن"
    ]
    static let profanitySqueezed: [String] = [
        "arsehole",
        "bastard",
        "bitch",
        "bitches",
        "cock",
        "cunt",
        "dickhead",
        "fuck",
        "fucked",
        "fucker",
        "fucking",
        "motherfucker",
        "prick",
        "shit",
        "slut",
        "twat",
        "wanker",
        "whore",
        "ابن الكلب",
        "العنه",
        "حيوان قذر",
        "خرا",
        "زفت",
        "طز",
        "كسمك",
        "كلب ابن كلب",
        "يلعن"
    ]

    private static let strip: Set<Character> = {
        var set: Set<Character> = ["\u{0640}", "\u{200C}", "\u{200D}", "\u{200E}", "\u{200F}", "\u{0670}"]
        for code in 0x064B...0x065F { set.insert(Character(UnicodeScalar(code)!)) }
        for code in 0x06D6...0x06ED { set.insert(Character(UnicodeScalar(code)!)) }
        return set
    }()

    private static let swap: [Character: Character] = [
        "\u{0623}": "\u{0627}", "\u{0625}": "\u{0627}", "\u{0622}": "\u{0627}",
        "\u{0671}": "\u{0627}", "\u{0649}": "\u{064A}", "\u{0629}": "\u{0647}",
        "\u{0624}": "\u{0648}", "\u{0626}": "\u{064A}",
        "0": "o", "1": "i", "3": "e", "4": "a", "5": "s", "7": "t", "@": "a", "$": "s",
    ]

    private static let separators: Set<Character> = [".", "-", "_", "*", "#", "%", "\u{2022}", "'", "\u{2019}"]

    /// Must agree, character for character, with `normalise` in the JavaScript
    /// copies. tools/check_wordlist.py holds all three to the same vectors.
    static func normalise(_ text: String, squeeze: Bool = false) -> String {
        var out = ""
        out.reserveCapacity(text.count + 2)
        var previous: Character = " "
        for raw in text.lowercased() {
            var character = swap[raw] ?? raw
            if strip.contains(character) { continue }
            if !character.isLetter { character = " " }
            if character == previous && (squeeze || character == " ") { continue }
            out.append(character)
            previous = character
        }
        return " " + out.trimmingCharacters(in: .whitespaces) + " "
    }

    /// "f.u.c.k" and "f-u-c-k" read as one word. A separator only counts when
    /// it sits between two letters, so hyphenated names survive.
    static func undotted(_ text: String) -> String {
        var out = ""
        let characters = Array(text)
        for (index, character) in characters.enumerated() {
            if separators.contains(character),
               index > 0, index + 1 < characters.count,
               characters[index - 1].isLetter, characters[index + 1].isLetter {
                continue
            }
            out.append(character)
        }
        return out
    }

    /// The first refused word, or nil. The caller decides how much to say; the
    /// app deliberately does not repeat the word back on screen.
    static func refusal(in text: String) -> String? {
        for candidate in [text, undotted(text)] {
            let plain = normalise(candidate)
            let tight = normalise(candidate, squeeze: true)
            for (words, squeezed) in groups {
                for word in words where plain.contains(" " + word + " ") { return word }
                for word in squeezed where tight.contains(" " + word + " ") { return word }
            }
        }
        return nil
    }

    private static var groups: [([String], [String])] {
        var all: [([String], [String])] = [(slurs, slursSqueezed), (sexual, sexualSqueezed)]
        if refuseProfanity { all.append((profanity, profanitySqueezed)) }
        return all
    }
}
